### PR TITLE
[SIW-224] Scaffold sd-jwt package

### PR DESCRIPTION
**Pull request by balanza**
#### List of Changes

* add `packages/sd-jwt`

#### Motivation and Context

This package will contain a typescript implementation of the [SD-JWT](https://datatracker.ietf.org/doc/draft-terbu-sd-jwt-vc/) standard.
The package is not meant to be published on public registries, so far; instead, it will be imported by other packages and apps in the solution.

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by balanza** [comment]
**question:**  I wonder if we should call the package `sd-jwt-vc`  as we are referencing https://datatracker.ietf.org/doc/draft-terbu-sd-jwt-vc/‏

**Review by grausof — APPROVED** [review]

**Review by hevelius — CHANGES_REQUESTED** [review]
Shouldn't be package name `packages/sd-jwt`?

**Comment by balanza** [comment]
> Shouldn't be package name directory `packages/sd-jwt`?

😱😱😱😱😱😱😱😱

Great catch! Thanks

**Review by hevelius — APPROVED** [review]
LGTM

**Pull request merged**
