### PR TITLE
GitHub federated identity

### PR DESCRIPTION
**Pull request by balanza**
#### List of Changes

* add federated identity for the current repository 

#### Motivation and Context

GitHub actions need to access Azure environments to run terraform plan/apply

⚠️ This IaC project has been moved from https://github.com/pagopa/eudi-wallet-it-wallet-solution and has been partially applied.

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by Krusty93** [comment]
@balanza Should this PR be discarded?

**Comment by balanza** [comment]
> @balanza Should this PR be discarded?

Do you think it's not needed?

**Comment by Krusty93** [comment]
> > @balanza Should this PR be discarded?
> 
> Do you think it's not needed?

My bad, I was assuming it was the old repo.

However I've got an error:

image

**Comment by balanza** [comment]
@Krusty93 weird, my local plan is fine:
```
Terraform will perform the following actions:

  # module.federated_identities.module.federated_cd_identity[0].azurerm_federated_identity_credential.identity_credentials["eudi-wallet-it-wallet-solution.environment.prod-cd"] will be destroyed
  # (because key ["eudi-wallet-it-wallet-solution.environment.prod-cd"] is not in for_each map)
  - resource "azurerm_federated_identity_credential" "identity_credentials" {
      - audience            = [
          - "api://AzureADTokenExchange",
        ] -> null
      - id                  = "/subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-identity-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/io-p-wallet-github-cd-identity/federatedIdentityCredentials/io-p-wallet-github-eudi-wallet-it-wallet-solution-environment-prod-cd" -> null
      - issuer              = "https://token.actions.githubusercontent.com" -> null
      - name                = "io-p-wallet-github-eudi-wallet-it-wallet-solution-environment-prod-cd" -> null
      - parent_id           = "/subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-identity-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/io-p-wallet-github-cd-identity" -> null
      - resource_group_name = "io-p-identity-rg" -> null
      - subject             = "repo:pagopa/eudi-wallet-it-wallet-solution:environment:prod-cd" -> null
    }

  # module.federated_identities.module.federated_cd_identity[0].azurerm_federated_identity_credential.identity_credentials["io-wallet.environment.prod-cd"] will be created
  + resource "azurerm_federated_identity_credential" "identity_credentials" {
      + audience            = [
          + "api://AzureADTokenExchange",
        ]
      + id                  = (known after apply)
      + issuer              = "https://token.actions.githubusercontent.com"
      + name                = "io-p-wallet-github-io-wallet-environment-prod-cd"
      + parent_id           = "/subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-identity-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/io-p-wallet-github-cd-identity"
      + resource_group_name = "io-p-identity-rg"
      + subject             = "repo:pagopa/io-wallet:environment:prod-cd"
    }

  # module.federated_identities.module.federated_cd_identity[0].azurerm_user_assigned_identity.identity will be updated in-place
  ~ resource "azurerm_user_assigned_identity" "identity" {
        id                  = "/subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-identity-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/io-p-wallet-github-cd-identity"
        name                = "io-p-wallet-github-cd-identity"
      ~ tags                = {
            "CostCenter"     = "TS310 - PAGAMENTI & SERVIZI"
            "CreatedBy"      = "Terraform"
            "Environment"    = "Prod"
            "ManagementTeam" = "IO Wallet"
            "Owner"          = "IO"
          ~ "Source"         = "https://github.com/pagopa/eudi-wallet-it-wallet-solution/blob/main/infra/identity/prod/westeurope" -> "https://github.com/pagopa/io-wallet"
        }
        # (5 unchanged attributes hidden)
    }

  # module.federated_identities.module.federated_ci_identity[0].azurerm_federated_identity_credential.identity_credentials["eudi-wallet-it-wallet-solution.environment.prod-ci"] will be destroyed
  # (because key ["eudi-wallet-it-wallet-solution.environment.prod-ci"] is not in for_each map)
  - resource "azurerm_federated_identity_credential" "identity_credentials" {
      - audience            = [
          - "api://AzureADTokenExchange",
        ] -> null
      - id                  = "/subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-identity-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/io-p-wallet-github-ci-identity/federatedIdentityCredentials/io-p-wallet-github-eudi-wallet-it-wallet-solution-environment-prod-ci" -> null
      - issuer              = "https://token.actions.githubusercontent.com" -> null
      - name                = "io-p-wallet-github-eudi-wallet-it-wallet-solution-environment-prod-ci" -> null
      - parent_id           = "/subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-identity-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/io-p-wallet-github-ci-identity" -> null
      - resource_group_name = "io-p-identity-rg" -> null
      - subject             = "repo:pagopa/eudi-wallet-it-wallet-solution:environment:prod-ci" -> null
    }

  # module.federated_identities.module.federated_ci_identity[0].azurerm_federated_identity_credential.identity_credentials["io-wallet.environment.prod-ci"] will be created
  + resource "azurerm_federated_identity_credential" "identity_credentials" {
      + audience            = [
          + "api://AzureADTokenExchange",
        ]
      + id                  = (known after apply)
      + issuer              = "https://token.actions.githubusercontent.com"
      + name                = "io-p-wallet-github-io-wallet-environment-prod-ci"
      + parent_id           = "/subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-identity-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/io-p-wallet-github-ci-identity"
      + resource_group_name = "io-p-identity-rg"
      + subject             = "repo:pagopa/io-wallet:environment:prod-ci"
    }

  # module.federated_identities.module.federated_ci_identity[0].azurerm_user_assigned_identity.identity will be updated in-place
  ~ resource "azurerm_user_assigned_identity" "identity" {
        id                  = "/subscriptions/ec285037-c673-4f58-b594-d7c480da4e8b/resourceGroups/io-p-identity-rg/providers/Microsoft.ManagedIdentity/userAssignedIdentities/io-p-wallet-github-ci-identity"
        name                = "io-p-wallet-github-ci-identity"
      ~ tags                = {
            "CostCenter"     = "TS310 - PAGAMENTI & SERVIZI"
            "CreatedBy"      = "Terraform"
            "Environment"    = "Prod"
            "ManagementTeam" = "IO Wallet"
            "Owner"          = "IO"
          ~ "Source"         = "https://github.com/pagopa/eudi-wallet-it-wallet-solution/blob/main/infra/identity/prod/westeurope" -> "https://github.com/pagopa/io-wallet"
        }
        # (5 unchanged attributes hidden)
    }

Plan: 2 to add, 2 to change, 2 to destroy.
```

**Comment by christian-calabrese** [comment]
I tried to plan and I got the same error as @Krusty93. Although the .terraform-version file is set to 1.3.8, the remote terraform state has been deployed with terraform version 1.7.5.

Updating the terraform version to 1.7.5 in the .terraform-version file fixes the issue.

**Review by christian-calabrese — APPROVED** [review]
LGTM

**Pull request merged**
