### PR TITLE
chore: renamed function app as io-wallet-user-func

### PR DESCRIPTION
**Pull request by silvicir**
#### Motivation and Context

So the workspace will be named as the deployed function app (which will be `io-p-itn-wallet-user-func-01`)

#### Checklist:

- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by silvicir** [comment]
@Krusty93

**Comment by Krusty93** [comment]
> @Krusty93 what do you think?

Unfortunately the storage account behind the function has a character limit of 24 :( It'd be `iopitnwalletsolutionuserst01` with 28 chars. It's the only chars limit we have

**Comment by grausof** [comment]
At this point I would say leave `io-p-itn-wallet-user-func-01`. @silvicir

**Comment by silvicir** [comment]
> At this point I would say leave `io-p-itn-wallet-user-func-01`. @silvicir

yes and the domain will be `wallet` everywhere

**Review by Krusty93 — APPROVED** [review]

**Pull request merged**
